import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../Components/theme-provider";
import Dropdown_theme from "@/Components/Dropdown-theme";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="system">
      <body>
        <ThemeProvider
        // attribute="class"
        // defaultTheme="system"
        // enableSystem
        // disableTransitionOnChange
        >
          <div className="flex justify-end">
            <Dropdown_theme />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
