import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../Components/theme-provider";
import Dropdown_theme from "@/Components/Dropdown-theme";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <ThemeProvider
        // attribute="class"
        // defaultTheme="system"
        // enableSystem
        // disableTransitionOnChange
        >
          <div className="navbar bg-base-200">
            <div className="ps-4">
              <a className="text-lg font-bold">SMART</a>
            </div>
            <div className="flex grow justify-end px-2">
              <Dropdown_theme />
            </div>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
